export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="__variable_188709 __variable_9a8899 antialiased">
      {children}
    </body>
  );
}
